name: Run All Tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - ready_for_review
      - review_requested
      - synchronize
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Run All tests
        run: |
          nix flake check --keep-going
